### ISSUE TITLE
prettify json file | Formatting.Indented

### ISSUE THREAD

**Issue by boexler** [dazinator/Dazinator.Extensions.WriteableOptions#2]
Is it possible to add `Formatting.Indented` / prettify the json output file?

instead of
```json
{"Logging":{"LogLevel":{"Default":"Information","Microsoft":"Warning","Microsoft.Hosting.Lifetime":"Information"}},"AllowedHosts":"*","ZlsOptions":{"HelloWorld":"success","ReturnUnknownCarriers":false,"RequireRoute":true,"LayoutFile":"D:\\Repositories\\gitlab.haprotec\\dotNet\\HtSuite\\server\\HtSuite.Server.Template\\bin\\Debug\\netcoreapp3.1\\ActiveConfig\\Layout.xml"},"ServerOptions":{"ServerPort":0,"ServerUrl":"123.456"}}
```

I would prefer

```json
{
	"Logging": {
		"LogLevel": {
			"Default": "Information",
			"Microsoft": "Warning",
			"Microsoft.Hosting.Lifetime": "Information"
		}
	},
	"AllowedHosts": "*",
	"ZlsOptions": {
		"HelloWorld": "success",
		"ReturnUnknownCarriers": false,
		"RequireRoute": true,
		"LayoutFile": "D:\\Repositories\\gitlab.haprotec\\dotNet\\HtSuite\\server\\HtSuite.Server.Template\\bin\\Debug\\netcoreapp3.1\\ActiveConfig\\Layout.xml"
	},
	"ServerOptions": {
		"ServerPort": 0,
		"ServerUrl": "123.456"
	}
}
```

**Comment by dazinator** [comment]
Yeah I'd like this too! Any chance of a PR?

**Comment by dazinator** [comment]
I'm specifying `indented` for the json serialisation options but for some reason this has no effect. I'll need to investigate, perhaps doing something stupid and these options may be bypassed somehow: 
https://github.com/dazinator/Dazinator.Extensions.WritableOptions/blob/develop/src/Dazinator.Extensions.Options.Updatable/JsonUpdatableOptions.cs#L18

**Comment by dazinator** [comment]
Ah so I have found the bug.
I am not passing the serializer options into the Utf8JsonWriter constructor here: https://github.com/dazinator/Dazinator.Extensions.WritableOptions/blob/develop/src/Dazinator.Extensions.Options.Updatable/JsonUpdatableOptions.cs#L44

If you have time to submit a PR for that I will accept and hopefully that should fix this issue. Otherwise I'll try and get to it at some point in the future!

**Comment by boexler** [comment]
Maybe this needs some refactoring. Because you have added the options with this call, but at the end it's ignored 😄✌

```cs
writer.WriteJsonWithModifiedSection<TOptions>(reader, _sectionName, optionValue, _defaultSerializerOptions);
```

**Comment by dazinator** [comment]
I've pushed a smaller / easier (for me) change for now, which just takes the "indentiing" option from the serialisation options, [when doing the writing](https://github.com/dazinator/Dazinator.Extensions.WritableOptions/commit/787f2afe12ecde9d5239e421e26012991bc56b2b#diff-629e107a12f47bbaa6e87bd329efae57R46)

At the moment this just uses the default serialization options which indenting is set to true.
This change won't provide a way to override the default serialisation options, that can be done as a seperate issue and would most likely be the one to think about ServiceCollectionExtensions refactoring.
