### ISSUE TITLE
Null value is not written

### ISSUE THREAD

**Issue by boexler** [dazinator/Dazinator.Extensions.WriteableOptions#3]
I have a class `ServerOptions` with only the `default` values.

```cs
public class ServerOptions
{
	/// <summary>
	/// Default listening port
	/// </summary>
	public int ServerPort { get; set; }

	/// <summary>
	/// Default listening url
	/// </summary>
	public string ServerUrl { get; set; }
}
```

which produces the following json string:

```json
"ServerOptions": {
	"ServerPort": 0
}
```
In my opinion the `ServerUrl` is missing here. So the json string should be

```json
"ServerOptions": {
	"ServerPort": 0,
	"ServerUrl":
}
```
or
```json
"ServerOptions": {
	"ServerPort": 0,
	"ServerUrl": null
}
```

**Comment by dazinator** [comment]
Yeah, I think this is down to the fact that at the moment, I use default SerializationOptions as specified here: https://github.com/dazinator/Dazinator.Extensions.WritableOptions/blob/develop/src/Dazinator.Extensions.Options.Updatable/JsonUpdatableOptions.cs#L49

But there is no way for you to override these options with your own.

I think we need to allow overriding the default serialisation options perhaps:

e.g

```
       public SomeController(IOptionsUpdater<TestOptions> updater)
	{
	
	   updater.Update((options)=>{options.SomeFlag = true; }, new JsonSerializerOptions() { IgnoreNullValues = true, WriteIndented = true };);

	   // The "foo:bar" section of the "mysettings.json" file has now been updated.
	}

```

**Comment by boexler** [comment]
A better solution would be in the `services.ConfigureJsonUpdatableOptions()`. method, what do you think?
I don't think that you have to change these options again afterwards?

**Comment by dazinator** [comment]
Yeah I agree, was thinking the same as soon as wrote that ;-)

**Comment by boexler** [comment]
Actually I'm stuck on the PR. I'm currently working on the `ServiceCollectionExtensions.cs` and I wonder if it is really necessary to have so many different methods.

I will add the following method for my purposes. Maybe you agree that 80% of the remaining methods could be deleted.

```cs
public static IServiceCollection ConfigureJsonUpdatableOptions<TOptions>(this IServiceCollection services, string filePath, params IConfigurationSection[] configurationSections) where TOptions : class, new()
{
	foreach (var section in configurationSections)
	{
		services.ConfigureJsonUpdatableOptions(section, new FileJsonStreamProvider<TOptions>(filePath), DefaultSerializerOptions, false);
	}

	return services;
}

public static IServiceCollection ConfigureJsonUpdatableOptions<TOptions>(this IServiceCollection services, string filePath, JsonSerializerOptions jsonSerializerOptions, params IConfigurationSection[] configurationSections) where TOptions : class, new()
{
	foreach (var section in configurationSections)
	{
		services.ConfigureJsonUpdatableOptions(section, new FileJsonStreamProvider<TOptions>(filePath), jsonSerializerOptions, false);
	}

	return services;
}
```

This would result in the following easy call:

```cs
services.ConfigureJsonUpdatableOptions("Path/To/Config.json", new JsonSerializerOptions
{
	IgnoreNullValues = false,
	WriteIndented = true
}, Configuration.GetSection(nameof(ServerOptions)), Configuration.GetSection(nameof(ZlsOptions)), Configuration.GetSection(nameof(CustomerOptions)));
```

or if you want the `default` serializer

```cs
services.ConfigureJsonUpdatableOptions("Path/To/Config.json", Configuration.GetSection(nameof(ServerOptions)), Configuration.GetSection(nameof(ZlsOptions)), Configuration.GetSection(nameof(CustomerOptions)));
```

And can you give me a hint whats the difference between the naming `ConfigureJsonUpdatableOptions` and `AddJsonUpdatableOptions`? Because they use the same underlying method..

**Comment by dazinator** [comment]
Yeah I'm up for simplifying it but the difference between Add and Configure is that the "configure" ones also configure the IOptions for you. Where as the Add ones rely on the IOptions already being configured. In one of my applications I needed to use ServiceCollection.AddOptions() myself to add options with pre and post configuration and manually bind to a config section. So in that application I configure the TOptioms myself using AddOptions and then I just call the "Add" version of these methods so it doesnt duplicate the configure options part.. the configure versions of the method just do a very basic bind to a config section  for you, without any of the options extras that you can do through AddOptions yourself like pre and post.. if there is a better way I'd be up for a change

**Comment by boexler** [comment]
I made a PR. Please have a look at it. I refactored the `ConfigureJsonUpdateableOptions` methods for more simplicity. 

I have removed all methods that use lambda for read and write methods. In my opinion you should write new methods for this, e.g. `ConfigureInMemoryUpdateableOptions`

**Comment by dazinator** [comment]
Thanks for your efforts.
I decided to fix this issue with a path that took less effort on my behalf. I may have adopted your changes but I thought the scope was too broad in nature and it wasn't in a readily adoptable format (i.e PR with changes implemented and all tests passing). This would have meant refactoring a lot of tests too on my part.
It is something I would consider doing in future but probably warrants a seperate issue.

In the meantime I have fixed this issue with a smaller change that allows JsonSerializationOptions to be supplied as an additional parameter at registration time with the existing APIs. I've added a test case for that, specifically to check null value handling can now be changed.

You can also provide an optional JsonSerialisationOptions at Update() time, which will override the default serialisation options if provided. I'm honestly not sure if that option is going to be of best use, but whilst I was in the area I thought there would be no harm in enabling it as a possiblity.

Have updated the readme to add a bit about Configure vs Add.

**Comment by dazinator** [comment]
Actually I'll get rid of the optional serialisation options supplied to Update() - that couples usage to JSON too much, i'd prefer the underlying store to be all configured and registration time and for general usage / consumption of IUpdateableOptions to be agnostic of any particular medium as possible.

**Comment by boexler** [comment]
You're welcome. My words, that's why I've completely rewritten the whole thing. 

With my approach, I think you have a very clean start to configure the configuration and underlaying base.

If you need further support (InMemory), I think you should use a new approach `ConfigureInMemoryUpdateableOptions`. However, this means a complete revision of the project structure. Nevertheless I hope to have given you a good approach, should you have the time and desire to realize it in the future. 😄

```cs
services.ConfigureJsonUpdateableOptions(
		Path.Combine(Constants.FolderPaths.ActiveConfig, "appsettings.json"), new JsonSerializerSettings
		{
			Formatting = Formatting.Indented,
			NullValueHandling = NullValueHandling.Include
		})
	.AddConfigSection<CustomerOptions>(Configuration.GetSection(nameof(CustomerOptions)))
	.AddConfigSection<ServerOptions>(Configuration.GetSection(nameof(ServerOptions)))
	.AddConfigSection<ZlsOptions>(Configuration.GetSection(nameof(ZlsOptions)))
	// start setup routine to create entries in the appsettings.json
	.Setup();
```
